language: python
sudo: required
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up &
  - sleep 45 && docker exec -it ng /bin/bash -c "python -m pytest --cov=./"
  - docker exec -it ng /bin/bash -c "coverage run -a --source='.' manage.py test --settings=main_site.production_settings"
  - docker exec -it ng /bin/bash -c "coverage run -a --source='.' manage.py test --settings=main_site.settings"
after_success:
  - sudo cp /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code/.coverage ./
  - sed -i -e "s|/code|/home/travis/build/wschuell/ng_userxp|g" .coverage
  - codecov
